name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dotnet restore
        run: dotnet restore ./src/**/*.csproj
      - name: dotnet build
        run: dotnet build --configuration Release --no-restore ./src/**/*.csproj
      - name: create an image and push
        run: |
          cd ./src/SimpleBlog/
          chmod +x ./buildah-build.sh
          sudo ./buildah-build.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
